### ISSUE TITLE
Support Multiline Output for Objects

### ISSUE THREAD

**Issue by tayambamwanza** [kreuzerk/ng-web-console#3]
Right now the output in the console, will display in a single line as demonstrated in the image below.

![Screenshot from 2023-11-06 11-45-58](https://github.com/kreuzerk/ng-web-console/assets/11971384/f710f9f1-3907-4cd6-8873-e69940c97ea7)

It would be better to display objects over several lines.

**Comment by tayambamwanza** [comment]
@kreuzerk Sorry if it's a very simple issue, I just did it quickly as need to head off to work, if you need more info, please let me know.

**Comment by nivekcode** [comment]
@tayambamwanza no problem all good. thx a lot for creating the issue. 💪

**Comment by tayambamwanza** [comment]
Perfect!
