### ISSUE TITLE
Console doesnt clear with console.clear() command

### ISSUE THREAD

**Issue by tayambamwanza** [kreuzerk/ng-web-console#6]
One new requirement that's come up, when I run console.clear(), it doesn't clear the components ouput as well

**Comment by nivekcode** [comment]
Nice. Yeah that's a cool additional feature which can be implemented. For that we need another monkey patch for `console.clear`.

**Comment by nivekcode** [comment]
https://github.com/kreuzerk/ng-web-console/pull/7

**Comment by nivekcode** [comment]
@tayambamwanza this is out with 1.2.0
